version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: nest-docker-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NestJs
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=NestJs
      - JWT_SECRET_KEY=TesteDesafioTeddy
      - JWT_EXPIRATION_TIME=1h
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "3000:3000"

  nest-pgadmin4:
    image: dpage/pgadmin4
    container_name: nest-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
